name: Goldbach

on:
  workflow_dispatch:
    inputs:
      c:
        description: 'Slice index (to 25)'
        type: number
        required: true
        default: 10

jobs:
  bench:
    name: Bench Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Preparations
        run: |
          sudo apt update
          sudo apt install -y gfortran build-essential
 
      - name: Execution
        run: |
          cat goldbach.f
          gfortran -o goldbach goldbach.f -w -march=native -O4 -std=legacy
          ./goldbach <<< ${{ inputs.c }}
        timeout-minutes: 25
